/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    SealedBidFeedlot: {
      address:
        "0x6a2c293fb7e6b458e0574a4a038282045853204e91d4459ee0fced35b2427e5",
      abi: [
        {
          type: "impl",
          name: "SealedBidFeedlotImpl",
          interface_name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::internal::bounded_int::BoundedInt::<0, 30>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::SealedBidFeedlot::LotInfo",
          members: [
            {
              name: "productor",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "raza",
              type: "core::felt252",
            },
            {
              name: "peso_inicial",
              type: "core::integer::u256",
            },
            {
              name: "cantidad_animales",
              type: "core::integer::u256",
            },
            {
              name: "metadata_uri",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "start_time",
              type: "core::integer::u64",
            },
            {
              name: "duration",
              type: "core::integer::u64",
            },
            {
              name: "finalizado",
              type: "core::bool",
            },
            {
              name: "mejor_puja",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
          items: [
            {
              type: "function",
              name: "create_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "productor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "raza",
                  type: "core::felt252",
                },
                {
                  name: "peso_inicial",
                  type: "core::integer::u256",
                },
                {
                  name: "cantidad_animales",
                  type: "core::integer::u256",
                },
                {
                  name: "metadata_uri",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "duration",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "commit_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reveal_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nonce",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "finalize_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_winning_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_info",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::SealedBidFeedlot::LotInfo",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_count",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x59e3e9f707322d814bf326672207fa551a6b7f4a48cf8eb7533993cab2a29e9",
    },
  },
} as const;

export default deployedContracts;
